version: "3.9"

services:
  db:
    image: postgres:16
    container_name: memeup_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-memeup}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-memeup}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: memeup_api
    working_dir: /app/src/Memeup.Api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8080
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      # Разрешенные источники CORS (CSV)
      Cors__AllowedOrigins: ${CORS_ALLOWED_ORIGINS:-http://localhost:4200}
      # Подключение к БД (используем сервис "db" как host)
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=${POSTGRES_DB:-memeup};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres}

       # === JWT (из .env) ===
      JWT__Issuer: ${JWT__Issuer:-memeup}
      JWT__Audience: ${JWT__Audience:-memeup_frontend}
      JWT__Key: ${JWT__Key:-super_secret_dev_key_change_me}
      JWT__LifetimeMinutes: ${JWT__LifetimeMinutes:-60}

      # === сидинг админа (из .env) ===
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-Admin123!}

    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ./src/Memeup.Api:/app/src/Memeup.Api
      - uploads_data:/app/uploads
      - ./.config:/app/.config
    depends_on:
      db:
        condition: service_healthy
    command: [ "bash", "-lc", "dotnet tool restore && dotnet watch run --urls http://0.0.0.0:8080" ]

  # pgadmin (опционально) — раскомментируй блок при необходимости
  # pgadmin:
  #   image: dpage/pgadmin4:8
  #   container_name: memeup_pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
  #   ports:
  #     - "${PGADMIN_PORT:-8081}:80"
  #   depends_on:
  #     - db

volumes:
  db_data:
  uploads_data:
