// <auto-generated />
using System.Reflection;
using Memeup.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Memeup.Api.Migrations
{
    [DbContext(typeof(MemeupDbContext))]
    [Migration("20250922150000_TaskImageMetadata")]
    partial class TaskImageMetadata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            var snapshot = new MemeupDbContextModelSnapshot();
            var buildModel = typeof(MemeupDbContextModelSnapshot).GetMethod(
                "BuildModel",
                BindingFlags.Instance | BindingFlags.NonPublic);
            buildModel!.Invoke(snapshot, new object[] { modelBuilder });
#pragma warning restore 612, 618
        }
    }
}
