name: memeup-api-prod

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

  api:
    image: ghcr.io/${GHCR_OWNER:-your-gh-username}/memeup.api:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:8080

      # Строка подключения к внутренней БД
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

      # CORS
      Cors__AllowedOrigins: ${CORS_ALLOWED_ORIGINS}

      # JWT
      JWT__Issuer: ${JWT__Issuer}
      JWT__Audience: ${JWT__Audience}
      JWT__Key: ${JWT__Key}
      JWT__LifetimeMinutes: ${JWT__LifetimeMinutes:-60}

      # сидинг админа
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    volumes:
      - uploads_data:/app/uploads
    networks:
      - internal
      - traefik_proxy

    labels:
      # === Traefik (пример, подставь свой домен) ===
      - "traefik.enable=true"
      - "traefik.http.routers.memeup-api.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.memeup-api.entrypoints=websecure"
      - "traefik.http.routers.memeup-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.memeup-api.loadbalancer.server.port=8080"

networks:
  internal:
    driver: bridge
  traefik_proxy:
    external: true

volumes:
  db_data:
  uploads_data:
